apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-hunqwkxw
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/backend-tests-go-hunqwkxw:15f16c71ba189077ab995b25bbf6c722de0937a0@sha256:c7aa290e566fa6cea43ae1c0981f5941cef630a793f3f96bf2da92134e2f6d80
          name: container-image
