apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: backend-tests-go-hunqwkxw
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/backend-tests-go-hunqwkxw:924f764d1371ad2840ecc2e096c995cb1b186499@sha256:08bd7d4e2f1ef47d8f96834c8bc731defa1bd9532c269bb4f9536d7a2ccca283
        name: container-image  
